### ISSUE TITLE
Usage without interrupt

### ISSUE THREAD

**Issue by Elektrik1** [sparkfun/SparkFun_WebServer_ESP32_W5500#4]
Is there a way to use this library without interrupt enabled?
Tried to set pin_W5500_INT to -1, but it errors.

Unfortunately I have a hardware where INT is not connected to ESP32, hence cannot modify the hardware.

**Comment by PaulZC** [comment]
Hi Julius (@Elektrik1 ),

Sorry, no, at least I don't think so. The library and the underlying IDF code relies heavily on the interrupt to (e.g.) identify when a new [packet has been received](https://github.com/sparkfun/SparkFun_WebServer_ESP32_W5500/blob/9c58e0b1df5eb93ef564b95b3e820304ced74f02/src/w5500/esp_eth/esp_eth_mac_w5500.c#L448).

Best wishes,
Paul
