### ISSUE TITLE
Does not work with esp32 arduino >= 3.0

### ISSUE THREAD

**Issue by Elektrik1** [sparkfun/SparkFun_WebServer_ESP32_W5500#6]
Changes in esp32 Arduino 3.0 breaks compatibility.
IPv6Address is removed and now used with single IPAddress variable.
WifiClient is now defined in WiFi.h and throws an error on 'friend class WiFiClient'.

**Comment by PaulZC** [comment]
Hi Julius (@Elektrik1 ),

Yes, thanks, we were aware of this issue.

We have no plans to try and make this library compatible with arduino-esp32 v3.0. v3.0 includes full Arduino support for the W5500. It works very well and provides full support for interrupts. We have switched to ```WebServer``` which comes built-in with v3.0. The only complication is that ```WebServer``` does not support sockets, so we use ```esp_http_server``` for those - on port 81.

I am going to close this issue, but will pin it to make it easier to find.

Best wishes,
Paul

**Comment by jurepetrovic** [comment]
Hi @PaulZC, 

thank you for your input. 
If you switched to W5500 and esp32 core 3 with WebServer, where could I find a working example?

**Comment by PaulZC** [comment]
Hi Jure (@jurepetrovic ),

We don't have a stand-alone example. But we do use WebServer in our RTK Everywhere firmware. Perhaps you can copy what you need from that?

https://github.com/search?q=repo%3Asparkfun%2FSparkFun_RTK_Everywhere_Firmware%20webserver&type=code

Best wishes,
Paul

**Comment by jurepetrovic** [comment]
Hello @PaulZC, 

thanks for your help. Checked quickly, but don't know if helps. 
I'm trying to use: 
* esp32 core v3.05
* built in Web server 
* W5500 network module

Tried this example code: 
`#include <SPI.h>
#include <WiFi.h>
#include <Ethernet.h>
#include <WebServer.h>
#include <WebServer.h>
#include <esp_event.h>
#include <esp_netif.h>

// Define the CS pin for W5500 as GPIO10
#define W5500_CS_PIN 10  // Chip Select pin for W5500


// Network settings (adjust for your network)
byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };  // MAC address (unique for each device)
IPAddress ip(192, 168, 0, 177);                       // Static IP address
IPAddress gateway(192, 168, 0, 2);                    // Gateway IP
IPAddress subnet(255, 255, 255, 0);                   // Subnet mask

// Create an instance of WebServer on port 80
WebServer server(80);

void setup() {

  Serial.begin(115200);

  // Initialize network interface and event loop (new method in ESP32 core 3.x)
  esp_netif_init();                 // Initialize the network interface
  esp_event_loop_create_default();  // Create the default event loop

  // Initialize Ethernet
  Ethernet.init(W5500_CS_PIN);  // CS pin for W5500 module

  if (Ethernet.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    Ethernet.begin(mac, ip, gateway, gateway, subnet);  // Use static IP
  }

  delay(5000);  // Give Ethernet some time to initialize

  // Print the local IP address to the serial monitor
  Serial.print("Server IP Address: ");
  Serial.println(Ethernet.localIP());
  Serial.print("Subnet Mask: ");
  Serial.println(Ethernet.subnetMask());
  Serial.print("Gateway IP: ");
  Serial.println(Ethernet.gatewayIP());

  // Handle POST requests to /ping
  server.on("/ping", HTTP_POST, []() {
    String response = "{\"response\":\"pong\"}";
    server.send(200, "application/json", response);  // Use WebServer's send method
  });


  // Start the web server
  server.begin();
  Serial.println("Web server started.");
}

void loop() {

  server.handleClient();
  delay(5);
}`

Funny thing is, I get IP and ping works. 
But Web Server does not listen. It's connection refused on port 80. 

entry 0x403c98ac
Server IP Address: 192.168.0.167
Subnet Mask: 255.255.255.0
Gateway IP: 192.168.0.2
Web server started.

Maybe that gives you any idea? 
Thanks!

**Comment by PaulZC** [comment]
You haven't added a handler for "/":

https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/1411506be7b6a6d86d7c3eb71fcb5e51e0a7cc74/Firmware/RTK_Everywhere/Form.ino#L341-L344

**Comment by jurepetrovic** [comment]
@PaulZC 

I have 2 handlers now. Also included root to the previous ping. 
It gets IP and pings it, but seems like webserver is not listening on ethernet. 

Are you sure W5500 is supported in esp32 core 3.x? 
I have connected miso, mosi, cs, sck, gnd, 3.3V.
Do I need interrupt too? 

No more ideas...


  // Handle POST requests to /ping
  server.on("/ping", HTTP_POST, []() {
    String response = "{\"response\":\"pong\"}";
    server.send(200, "application/json", response);  // Use WebServer's send method
  });

  server.on("/", HTTP_GET, []() {
    server.sendHeader("Content-Encoding", "gzip");
    server.send_P(200, "text/html", "BLABLA");
  });

**Comment by PaulZC** [comment]
Yes, you need the interrupt:

https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/1411506be7b6a6d86d7c3eb71fcb5e51e0a7cc74/Firmware/RTK_Everywhere/Ethernet.ino#L397

**Comment by PaulZC** [comment]
Maybe try starting from the [Espressif example](https://github.com/espressif/arduino-esp32/blob/master/libraries/Ethernet/examples/ETH_W5500_Arduino_SPI/ETH_W5500_Arduino_SPI.ino). Make sure that works, then add the WebServer?

Also, try setting the Core Debug Level to verbose. The debug messages in v3 of the core are really good.

**Comment by jurepetrovic** [comment]
Thanks, @PaulZC 

I connected INT pin and got it running with https://github.com/khoih-prog/AsyncWebServer_ESP32_SC_W5500/blob/main/examples/Async_PostServer/Async_PostServer.ino
However, I need to use core v2.0.17. 

I used Ethernet.h, Espressif example uses ETH.h
Will Webserver.h connect to that? I'll try to experiment a little and let you know.

**Comment by jurepetrovic** [comment]
@PaulZC  I tried espressif example and it works :) 

![image](https://github.com/user-attachments/assets/e613b364-83a3-4418-9c5e-bed974dbdc6d)



Now, If I understand this correctly, it should be able to use builtin WebServer, since it's independent from network, right?

Also, If I understand correctly I should be able to use server like this https://github.com/jackjansen/esp32_idf5_https_server since it uses IDF and is also therefore device independent?

Thanks, Thanks, Thanks, 
I guess I already owe you a sixpack of beers :)

**Comment by PaulZC** [comment]
Hi Jure (@jurepetrovic ),

No problem. I am glad it is working for you.

Yes, now you are connected, you can use WebServer. Ethernet is just the network - it works with WiFi too of course.

I haven't seen esp32_idf5_https_server before. It looks useful. Thank you for the link.

Best,
Paul

**Comment by jurepetrovic** [comment]
@PaulZC 

Currently this one is my preffered: 
https://github.com/hoeken/PsychicHttp

If I get this  one running with core v3.x and W5500 I got all my fundamental bases covered. 
Seems to me, that it should be compatible. 

Will provide working example if succeedeed.

Thanks :) 
Let me know how do I deliver beer :)

**Comment by PaulZC** [comment]
Thanks Jure - another useful link!

Don't worry about the beer. Please just "Pay it forward". Share a nice example when you have one. And give someone else a little help when they ask for it... ;-)
